CREATE TABLE IF NOT EXISTS category (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `available` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));

INSERT INTO CATEGORY VALUES (1, 'COMEDIA', TRUE); 
INSERT INTO CATEGORY VALUES (2, 'TERROR', FALSE); 
INSERT INTO CATEGORY VALUES (3, 'INTRIGA', TRUE); 